---
# tasks file for certbot

# Install certbot

  - name: Install epel-release
    yum:
      name: epel-release
      state: present
    tags: certbot

  - name: Install certbot
    yum:
      name: certbot
      state: present
    tags: certbot

# Install pexpect

  - name: Check if python pexpect is installed
    command: python2 -c "import pexpect"
    register: pexpect_check
    ignore_errors: yes
  - debug: msg="{{ pexpect_check.rc }}"
    tags: certificate

  - name: Install pip
    yum: name=python-pip state=present
    when: pexpect_check.rc >= 1
    tags: certificate

  - name: Install pip2 pexpect
    command: pip2 install pexpect
    when: pexpect_check.rc >= 1
    tags: certificate


# Install SSL certificate

  - name: Install SSL certificate
    expect:
      command: certbot certonly
      responses:
        'Select the appropriate number \[1\-2\] then \[enter\] \(press ' : '1'
        'Enter email address \(used for urgent renewal and security notices\)' : "{{ ssl_email }}"
        '\(Y\)es\/\(N\)o:' : 'Y'
        'Please enter in your domain name\(s\)' : "{{ registry_host }}"
    tags: certificate

# Copy certs to cert directory

  - name: Make sure {{ mount_dir }}/certs directory exists
    file:
      path: "{{ mount_dir }}/certs"
      state: directory

  - name: Copy certificates to {{ mount_dir }}/certs
    copy:
      src: /etc/letsencrypt/live/{{ registry_host }}/{{ item }}
      dest: "{{ mount_dir }}/certs"
      remote_src: yes
    loop:
      - cert.pem
      - chain.pem
      - fullchain.pem
      - privkey.pem 
